<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.6" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="DLL_ConnectionToDatabase">
      <HintPath>..\..\DLL_ConnectionToDatabase\DLL_ConnectionToDatabase\bin\Debug\net8.0\DLL_ConnectionToDatabase.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="CustomElements\Groups\CommentBlock.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Pages\PageEditConcept.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Pages\PageAdmin.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Page Update="CustomElements\Styles\MaxHeightInTable.xaml">
      <SubType>Designer</SubType>
    </Page>
    <Page Update="Pages\PageAdmin.xaml">
      <SubType>Designer</SubType>
    </Page>
  </ItemGroup>

</Project>
